ALTER TABLE artifacts ADD COLUMN title_en VARCHAR(300) NULL;
ALTER TABLE artifacts ADD COLUMN summary_en VARCHAR(1000) NULL;
ALTER TABLE articles ADD COLUMN title_en VARCHAR(300) NULL;
ALTER TABLE articles ADD COLUMN summary_en VARCHAR(1000) NULL;
