-- Fill missing translations only; never overwrite an editor's existing translation.
UPDATE artifacts SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'Heluo Bronze Ding (Digital Reconstruction)'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'Explore the form and details of a bronze ding through a digital reconstruction.') WHERE slug='heluo-bronze-ding';
UPDATE artifacts SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'Water-bird Bronze Sculpture (Concept)'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'A water-bird form connects close observation of nature with an imagined ancient object.') WHERE slug='water-bird-bronze';
UPDATE artifacts SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'Heluo-pattern Bronze Jue (Concept)'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'An original concept object inspired by Heluo patterns, with a light story-led entry into form and motif.') WHERE slug='heluo-bronze-jue';
UPDATE artifacts SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'River-map Jade Bi (Concept)'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'A jade disc follows the river as a visual thread between ritual, space and memory.') WHERE slug='river-map-jade-bi';
UPDATE artifacts SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'Painted Water-pattern Jar (Concept)'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'Water patterns and earthen rhythm open a glimpse into prehistoric life along the river.') WHERE slug='painted-pottery-water-jar';
UPDATE artifacts SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'River-map Pattern Stone (Concept)'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'A concept stone connects Heluo symbols with the memory of place and landscape.') WHERE slug='river-map-pattern-stone';
UPDATE articles SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'Why does negative space help an exhibit stand out?'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'Digital exhibitions need room to breathe between objects, words and the viewer’s gaze.') WHERE slug='why-negative-space-matters';
UPDATE articles SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'Reading the river as a timeline: Heluo culture for a new generation'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'Trace the links between water, settlements and motifs so tradition becomes more than a textbook term.') WHERE slug='river-as-timeline';
UPDATE articles SET title_en=COALESCE(NULLIF(TRIM(title_en),''),'Three questions to ask when viewing bronze for the first time'), summary_en=COALESCE(NULLIF(TRIM(summary_en),''),'Start with form, motifs and use instead of memorizing dates and terminology.') WHERE slug='how-to-read-bronze';
