import { computed, ref } from 'vue'

type Locale = 'zh-CN' | 'en-US'
const current = ref<Locale>((localStorage.getItem('heluo.locale') as Locale) || 'zh-CN')
const dictionary = {
  'zh-CN': { explore:'探索馆藏', exhibits:'数字展厅', appointment:'预约参观', shop:'河洛文创', login:'登录', admin:'内容管理', hero:'让传统文化\n成为今天的灵感。', heroCopy:'面向年轻文化探索者的数字博物馆：先在线探索故事与 3D 展项，再决定是否线下参观。', start:'开始探索', enter:'进入数字展厅', language:'EN', footer:'河洛数字博物馆 · 线上探索，线下相见', feature1Title:'故事化馆藏',feature1Text:'通过主题、文物和文章建立易理解的文化探索路径。',feature2Title:'互动 3D 展项',feature2Text:'加载自主创作的模型，支持旋转、缩放与展项说明。',feature3Title:'线上线下联动',feature3Text:'探索后预约参观，继续收藏有文化故事的原创文创。', auth:{login:'登录',register:'创建账号',forgot:'找回密码',reset:'设置新密码',intro:'登录后可以维护个人资料、预约参观和文创订单。管理员账号将进入后台管理。',username:'用户名',nickname:'昵称',email:'邮箱',emailOptional:'（注册时可选）',phoneOptional:'手机号（可选）',password:'密码',token:'重置令牌',submitting:'处理中…',back:'返回登录',create:'创建账号',forgotAction:'忘记密码'}, booking:{title:'给线下相见，留一个时间。',intro:'先在线探索，再选择适合自己的开放时段。提交后状态为“待确认”，管理员处理结果会发送到联系人邮箱。',loading:'正在读取开放时段…',empty:'未来两周暂未开放预约时段，请稍后再来。',remaining:'剩余',people:'人',form:'填写预约信息',selected:'已选择：',visitors:'参观人数',name:'联系人姓名',phone:'联系人手机号',email:'联系人邮箱',notes:'备注（可选）',submit:'提交预约',note:'可在开始前 2 小时取消；未登录时会先跳转至登录页面。',loadError:'开放时段暂时无法读取，请稍后重试。',submitError:'预约暂时未提交成功，请检查信息后重试。',loginRequired:'请先登录，再提交预约。',pastDate:'参观日期不能早于今天，请重新选择。',noCapacity:'该时段名额刚刚已满，请重新选择。',slotUnavailable:'该时段刚刚不可预约，请重新选择。',invalidForm:'预约信息不完整或格式不正确，请检查后重试。'}, shopText:{title:'把喜欢的文化故事，带回日常。',intro:'首批商品均为项目组自主创作的概念文创。第一版不含物流与真实支付，仅演示购物车和模拟支付流程。',loading:'正在加载文创商品…',remaining:'剩余',items:'件',add:'加入购物车',cart:'购物车',loginTip:'登录后即可加入商品并完成模拟支付。',empty:'购物车还是空的。',email:'通知邮箱',total:'合计',pay:'模拟支付'} },
  'en-US': { explore:'Explore', exhibits:'3D Gallery', appointment:'Visit Booking', shop:'Museum Store', login:'Sign in', admin:'Content Admin', hero:'Civilization never\nstands still.', heroCopy:'Along the Heluo rivers, the thread of civilization continues. Every artifact is a witness to time, connecting the past, the present and what comes next.', start:'Explore Heluo', enter:'Open 3D gallery', language:'中文', footer:'Heluo Digital Museum · Explore online, meet offline.', feature1Title:'Story-led collection',feature1Text:'Use themes, artifacts and articles to create an easy cultural exploration path.',feature2Title:'Interactive 3D exhibits',feature2Text:'Load self-created models with rotation, zoom and exhibit notes.',feature3Title:'Online-to-offline connection',feature3Text:'Book a visit after exploring, then discover original cultural products.', auth:{login:'Sign in',register:'Create account',forgot:'Reset password',reset:'Set new password',intro:'Sign in to manage your profile, visit bookings and museum-store orders. Administrators can access the management area.',username:'Username',nickname:'Display name',email:'Email',emailOptional:'(optional at registration)',phoneOptional:'Phone (optional)',password:'Password',token:'Reset token',submitting:'Working…',back:'Back to sign in',create:'Create account',forgotAction:'Forgot password'}, booking:{title:'Save a time for meeting offline.',intro:'Explore online first, then choose an open visit slot. New bookings wait for confirmation, and results are sent to the contact email.',loading:'Loading open visit slots…',empty:'There are no open slots in the next two weeks. Please check again later.',remaining:'Remaining',people:'people',form:'Booking details',selected:'Selected: ',visitors:'Visitors',name:'Contact name',phone:'Contact phone',email:'Contact email',notes:'Notes (optional)',submit:'Submit booking',note:'You may cancel up to two hours before the visit begins. Signing in is required to submit.',loadError:'Open visit times are temporarily unavailable. Please try again.',submitError:'The booking was not submitted. Check the details and try again.',loginRequired:'Please sign in before submitting a booking.',pastDate:'The visit date cannot be earlier than today. Choose another date.',noCapacity:'This time slot just filled up. Choose another slot.',slotUnavailable:'This time slot is no longer available. Choose another slot.',invalidForm:'Some booking details are missing or invalid. Check them and try again.'}, shopText:{title:'Bring culture stories into everyday life.',intro:'The first collection contains self-created concept products. Version one has no delivery or real payment; it demonstrates the cart and mock-payment flow only.',loading:'Loading museum-store products…',remaining:'Remaining',items:'items',add:'Add to cart',cart:'Cart',loginTip:'Sign in to add products and complete mock payment.',empty:'Your cart is empty.',email:'Notification email',total:'Total',pay:'Mock payment'} },
}
export function useLocale() {
  const t = computed(() => dictionary[current.value])
  function toggle() { current.value = current.value === 'zh-CN' ? 'en-US' : 'zh-CN'; localStorage.setItem('heluo.locale', current.value) }
  return { locale: current, t, toggle }
}
