import { randomUUID } from 'node:crypto'
import { expect, test } from '@playwright/test'
import { qualityEnvironment } from './environment'

test('真实 API 分页在语言切换、刷新和返回后保持正确', async ({ page, request }) => {
  const marker = `paging${randomUUID().slice(0, 8)}`
  const login = await request.post('/api/v1/auth/login', { data: qualityEnvironment.admin })
  expect(login.ok()).toBe(true)
  const headers = { Authorization: `Bearer ${(await login.json()).data.accessToken}` }
  const categories = await request.get('/api/v1/admin/categories', { headers })
  const categoryId = (await categories.json()).data[0].id
  const createdIds: number[] = []
  for (let i = 0; i < 25; i++) {
    const created = await request.post('/api/v1/admin/articles', { headers, data: {
      categoryId, slug: `${marker}-${i}`, title: `分页内容${i}`, summary: '分页中文摘要', content: '分页正文',
      titleEn: `${marker} ${i}`, summaryEn: 'Pagination summary',
    } })
    expect(created.ok()).toBe(true)
    const id = (await created.json()).data.id as number
    createdIds.push(id)
    const published = await request.post(`/api/v1/admin/articles/${id}/publish`, { headers })
    expect(published.ok()).toBe(true)
  }
  await page.addInitScript(() => { if (!localStorage.getItem('heluo.locale')) localStorage.setItem('heluo.locale', 'en-US') })
  await page.goto(`/explore?q=${marker}`)
  const cards = page.locator('.search-result-card')
  await expect(cards).toHaveCount(24)
  const firstPage = await cards.evaluateAll(elements => elements.map(element => element.getAttribute('href')))
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(cards).toHaveCount(1)
  await expect(page).toHaveURL(/page=2/)
  const last = await cards.first().getAttribute('href')
  expect(firstPage).not.toContain(last)
  await page.locator('.locale-toggle').click()
  await expect(page).toHaveURL(/page=2/)
  await expect(cards).toHaveCount(1)
  await expect(cards.first().locator('h3')).toContainText('分页内容')
  await page.reload()
  await expect(cards).toHaveCount(1)
  expect(await cards.first().getAttribute('href')).toBe(last)
  await cards.first().click()
  await expect(page.locator('h1')).toContainText('分页内容')
  await page.goBack()
  await expect(page).toHaveURL(/page=2/)
  await expect(cards).toHaveCount(1)
  await page.getByRole('button', { name: '上一页', exact: true }).click()
  await expect(cards).toHaveCount(24)
  expect(await cards.evaluateAll(elements => elements.map(element => element.getAttribute('href')))).toEqual(firstPage)
  for (const id of createdIds) expect((await request.post(`/api/v1/admin/articles/${id}/withdraw`, { headers })).ok()).toBe(true)
})

for (const locale of ['zh-CN', 'en-US']) for (const theme of ['light', 'dark']) for (const width of [390, 1440]) {
  test(`双语搜索与详情 ${locale} ${theme} ${width}`, async ({ page, request }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.addInitScript(({ locale, theme }) => {
      if (!localStorage.getItem('heluo.locale')) localStorage.setItem('heluo.locale', locale)
      localStorage.setItem('heluo.theme', theme)
    }, { locale, theme })
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/explore')
    await expect(page.locator('.gallery-object').first()).toBeVisible()
    const search = page.locator('input[type="search"]')
    await search.fill('BRONZE')
    await search.press('Enter')
    const cards = page.locator('.search-result-card')
    await expect(cards).toHaveCount(4)
    const urls = await cards.evaluateAll(elements => elements.map(element => element.getAttribute('href')))
    const firstTitle = await cards.first().locator('h3').innerText()
    await cards.first().click()
    await expect(page.locator('h1')).toHaveText(firstTitle)
    await page.goBack()
    await expect(cards).toHaveCount(4)
    await expect(search).toHaveValue('BRONZE')
    await page.reload()
    await expect(cards).toHaveCount(4)
    await page.locator('.locale-toggle').click()
    await expect(cards).toHaveCount(4)
    expect(await cards.evaluateAll(elements => elements.map(element => element.getAttribute('href')))).toEqual(urls)
    await expect(cards.first().locator('h3')).not.toHaveText(firstTitle)
    await search.fill('青铜')
    await search.press('Enter')
    await expect(cards).toHaveCount(4)
    await search.fill('jade')
    await search.press('Enter')
    await expect(cards).toHaveCount(1)
    await search.fill('nothing-will-match-this-query')
    await search.press('Enter')
    await expect(page.locator('.collection-state--empty')).toBeVisible()
    await page.locator('.museum-search-field__clear').click()
    await expect(page.locator('.gallery-object').first()).toBeVisible()
    await expect(cards).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(errors).toEqual([])
    const results = await request.get('/api/v1/search?keyword=bronze')
    expect(results.ok()).toBe(true)
    await page.screenshot({ path: `../artifacts/sitewide-quality/bilingual-${locale}-${theme}-${width}.png` })
  })
}

for (const resource of ['artifacts', 'articles']) {
  test(`后台双语维护闭环 ${resource}`, async ({ page, request, browser }) => {
    const suffix = randomUUID().slice(0, 8)
    const title = `双语验收${suffix}`
    const english = `Bilingual ${suffix}`
    const slug = `bilingual-${suffix}`
    await page.addInitScript(() => localStorage.setItem('heluo.locale', 'zh-CN'))
    await page.goto('/login?returnTo=%2Fadmin')
    await page.getByLabel('用户名', { exact: true }).fill(qualityEnvironment.admin.username)
    await page.locator('input[autocomplete="current-password"]').fill(qualityEnvironment.admin.password)
    await page.locator('.auth-panel form').getByRole('button', { name: '登录', exact: true }).click()
    await expect(page).toHaveURL(/\/admin$/)
    if (resource === 'articles') await page.getByRole('tab', { name: '文章', exact: true }).click()
    const form = page.locator('.admin-create form')
    await form.getByLabel('标题', { exact: true }).fill(title)
    await form.getByLabel(/^URL 标识/).fill(slug)
    await form.getByLabel('摘要', { exact: true }).fill('用于隔离环境验证的中文摘要。')
    await form.getByLabel('正文', { exact: true }).fill('隔离测试正文。')
    await form.getByLabel('英文标题（可选）', { exact: true }).fill(english)
    await form.getByLabel('英文摘要（可选）', { exact: true }).fill(`SummaryOnly${suffix}`)
    await page.screenshot({ path: `../artifacts/sitewide-quality/bilingual-admin-${resource}.png` })
    const created = page.waitForResponse(response => response.url().endsWith(`/api/v1/admin/${resource}`) && response.request().method() === 'POST')
    await form.getByRole('button', { name: '创建草稿', exact: true }).click()
    const createResponse = await created
    expect(createResponse.ok()).toBe(true)
    const id = (await createResponse.json()).data.id as number
    const row = page.locator('.admin-list article').filter({ hasText: title })
    await expect(row).toContainText('草稿')
    expect((await (await request.get(`/api/v1/search?keyword=${suffix}`)).json()).data.total).toBe(0)
    await row.getByRole('button', { name: '发布', exact: true }).click()
    await expect(row).toContainText('已发布')
    const publicContext = await browser.newContext({ baseURL: qualityEnvironment.baseURL, reducedMotion: 'reduce' })
    await publicContext.addInitScript(() => localStorage.setItem('heluo.locale', 'en-US'))
    const visitor = await publicContext.newPage()
    try {
      await visitor.goto(`/explore?q=SummaryOnly${suffix}`)
      await expect(visitor.locator('.search-result-card')).toHaveCount(1)
      await expect(visitor.locator('.search-result-card h3')).toHaveText(english)
      await visitor.locator('.search-result-card').click()
      await expect(visitor.locator('h1')).toHaveText(english)
      await expect(visitor.locator('.detail-summary')).toHaveText(`SummaryOnly${suffix}`)
      await row.getByRole('button', { name: '编辑', exact: true }).click()
      await expect(form.getByLabel('英文标题（可选）', { exact: true })).toHaveValue(english)
      await form.getByLabel('英文标题（可选）', { exact: true }).fill(`${english} Updated`)
      const saved = page.waitForResponse(response => response.url().endsWith(`/api/v1/admin/${resource}/${id}`) && response.request().method() === 'PATCH')
      await form.getByRole('button', { name: '保存修改', exact: true }).click()
      expect((await saved).ok()).toBe(true)
      await visitor.reload()
      await expect(visitor.locator('h1')).toHaveText(`${english} Updated`)
      await row.getByRole('button', { name: '编辑', exact: true }).click()
      await form.getByLabel('英文标题（可选）', { exact: true }).fill('')
      const partial = page.waitForResponse(response => response.url().endsWith(`/api/v1/admin/${resource}/${id}`) && response.request().method() === 'PATCH')
      await form.getByRole('button', { name: '保存修改', exact: true }).click()
      expect((await partial).ok()).toBe(true)
      await visitor.reload()
      await expect(visitor.locator('h1')).toHaveText(title)
      await expect(visitor.locator('.detail-summary')).toHaveText(`SummaryOnly${suffix}`)
      await row.getByRole('button', { name: '编辑', exact: true }).click()
      await form.getByLabel('英文摘要（可选）', { exact: true }).fill('')
      const cleared = page.waitForResponse(response => response.url().endsWith(`/api/v1/admin/${resource}/${id}`) && response.request().method() === 'PATCH')
      await form.getByRole('button', { name: '保存修改', exact: true }).click()
      expect((await cleared).ok()).toBe(true)
      await visitor.reload()
      await expect(visitor.locator('h1')).toHaveText(title)
      await expect(visitor.locator('.detail-summary')).toHaveText('用于隔离环境验证的中文摘要。')
      expect((await (await request.get(`/api/v1/search?keyword=SummaryOnly${suffix}`)).json()).data.total).toBe(0)
      await row.getByRole('button', { name: '撤回', exact: true }).click()
      await page.getByRole('dialog').getByRole('button', { name: '确认撤回', exact: true }).click()
      await expect(row).toContainText('已撤回')
      expect((await request.get(`/api/v1/${resource}/${slug}`)).status()).toBe(404)
    } finally { await publicContext.close() }
  })
}
